# Generated by Django 5.0.4 on 2024-04-23 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1A', '1A'), ('1Б', '1Б'), ('1B', '1B'), ('2A', '2A'), ('2Б', '2Б'), ('2B', '2B'), ('3A', '3A'), ('3Б', '3Б'), ('3B', '3B'), ('4A', '4A'), ('4Б', '4Б'), ('4B', '4B'), ('5A', '5A'), ('5Б', '5Б'), ('5B', '5B'), ('6A', '6A'), ('6Б', '6Б'), ('6B', '6B')], max_length=2, null=True)),
                ('summer', models.CharField(blank=True, choices=[('1A', '1A'), ('1Б', '1Б'), ('1B', '1B'), ('2A', '2A'), ('2Б', '2Б'), ('2B', '2B'), ('3A', '3A'), ('3Б', '3Б'), ('3B', '3B'), ('4A', '4A'), ('4Б', '4Б'), ('4B', '4B'), ('5A', '5A'), ('5Б', '5Б'), ('5B', '5B'), ('6A', '6A'), ('6Б', '6Б'), ('6B', '6B')], max_length=2, null=True)),
                ('autumn', models.CharField(blank=True, choices=[('1A', '1A'), ('1Б', '1Б'), ('1B', '1B'), ('2A', '2A'), ('2Б', '2Б'), ('2B', '2B'), ('3A', '3A'), ('3Б', '3Б'), ('3B', '3B'), ('4A', '4A'), ('4Б', '4Б'), ('4B', '4B'), ('5A', '5A'), ('5Б', '5Б'), ('5B', '5B'), ('6A', '6A'), ('6Б', '6Б'), ('6B', '6B')], max_length=2, null=True)),
                ('spring', models.CharField(blank=True, choices=[('1A', '1A'), ('1Б', '1Б'), ('1B', '1B'), ('2A', '2A'), ('2Б', '2Б'), ('2B', '2B'), ('3A', '3A'), ('3Б', '3Б'), ('3B', '3B'), ('4A', '4A'), ('4Б', '4Б'), ('4B', '4B'), ('5A', '5A'), ('5Б', '5Б'), ('5B', '5B'), ('6A', '6A'), ('6Б', '6Б'), ('6B', '6B')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=255)),
                ('phone', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new pereval'), ('pending', 'moderator is working'), ('accepted', 'pereval accepted'), ('rejected', 'pereval cancel')], default='new', max_length=10)),
                ('beauty_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.cords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.peruser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.pereval')),
            ],
        ),
    ]
