# Generated by Django 5.0.4 on 2024-04-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='pereval',
            old_name='coord',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='peruser',
            old_name='surname',
            new_name='fam',
        ),
        migrations.RenameField(
            model_name='peruser',
            old_name='patronymic',
            new_name='otc',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
