# Generated by Django 5.0.4 on 2024-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_rename_image_image_data_rename_coord_pereval_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
    ]
